# Build <project> / test compilation

name: BUILD

on: [push, pull_request]

# jobs
jobs:
  build-linux:
    name: Verify Compilation on ubuntu-latest
    runs-on: macos-latest
    steps:
    - name: Check out project code
      uses: actions/checkout@v2

    # attempt to use a cached version of this
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    
    # install Qt 6.2.0 at $GITHUB_WORKSPACE/qt/Qt/6.2.0/gcc_64/bin
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.0'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    # Runs a set of commands using the runners shell
    - name: Test compilation
      env:
        QTBIN: $GITHUB_WORKSPACE/qt/Qt/6.2.0/gcc_64/bin
      run: |
        cd $GITHUB_WORKSPACE
        export PATH=$PATH:$QTBIN
        qmake -config release actionstest.pro
        make -j2
        macdeployqt porymap.app -dmg

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: porymap.dmg
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

