# Build <project> / test compilation

on: [push, pull_request]

# jobs
jobs:
  build-linux:
    name: Verify Compilation on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    # attempt to use a cached version of this
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    
    # install Qt 5.14.2 at $GITHUB_WORKSPACE/qt/Qt/5.14.2/gcc_64/bin
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'linux'
        target: 'desktop'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        cached: 'false' #${{ steps.cache-qt.outputs.cache-hit }}

    - name: Check out project code
      uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Test compilation
      env:
        QTBIN: $GITHUB_WORKSPACE/qt/Qt/5.14.2/gcc_64/bin
      run: |
        echo looking for qmake in workspace
        ls $GITHUB_WORKSPACE/*
        ls $Qt5_DIR/*
#        export PATH=$PATH:/qt/5.14.2/gcc_64/bin/
#        qmake actiontest.pro
#        make -j2

