# Build <project> / test compilation

name: BUILD

on: [push, pull_request]

# jobs
jobs:
  build-linux:
    name: Verify Compilation on macos-latest
    runs-on: macos-latest
    steps:
    - name: Check out project code
      uses: actions/checkout@v2

    # attempt to use a cached version of this
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
    
    # install Qt 6.2.0 at $GITHUB_WORKSPACE/qt/Qt/6.2.0/gcc_64/bin
    # Runs a set of commands using the runners shell
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.*'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Configure
      run: qmake -config release

    - name: Compile
      run: |
        make
        macdeployqt actionstest.app -dmg

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: actionstest.dmg
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

