# This is a basic workflow to help you get started with Actions

name: RELEASE

# Trigger a relase build on tagged commits to master
on:
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build a relase version for macOS
  build-macos:
    name: Build project for macOS
    runs-on: macos-latest
    steps:
    - name: Check out project code
      uses: actions/checkout@v2

    # Install Qt 5.14.2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'mac'
        target: 'desktop'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        cached: 'false'

    # Runs a set of commands using the runners shell
    - name: Compile Project for macOS
      run: |
        cd $GITHUB_WORKSPACE
        export PATH=$PATH:$Qt5_DIR/bin
        qmake actionstest.pro -config release
        make -j2
        macdeployqt actionstest.app -dmg

    - name: Prep Release Directory
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir actionstest-mac
        cp actionstest.dmg actionstest-mac
        cp README.txt actionstest-mac

    - name: Bundle Release Directory
      if: startsWith(github.ref, 'refs/tags/')
      run: zip -r actionstest-mac.zip actionstest-mac

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: actionstest-mac.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build a relase version for Windows
  build-windows:
    name: Build project for Windows
    runs-on: windows-latest
    steps:
    - name: Check out project code
      uses: actions/checkout@v2

    # Install Qt 5.14.2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        cached: 'false'

    # Runs a set of commands using the runners shell
    - name: Compile Project for macOS
      run: |
        cd $GITHUB_WORKSPACE
        export PATH=$PATH:$Qt5_DIR/bin
        qmake actionstest.pro -config release
        make -j2
        windeployqt actionstest.exe

    - name: Prep Release Directory
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        mkdir actionstest-windows
        cp actionstest.exe actionstest-windows
        cp README.txt actionstest-mac

    - name: Bundle Release Directory
      if: startsWith(github.ref, 'refs/tags/')
      run: powershell.exe -Command "Compress-Archive -Path actionstest-windows -DestinationPath actionstest-windows.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: actionstest-windows.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
